
services:
    db:
        image: postgres:15
        container_name: task-db
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: tasks_db
        ports:
            - "5433:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "tasks_db"]
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 10s
    
    redis:
            image: redis:7
            container_name: task-redis
            restart: always
            ports:
                - "6379:6379"
            volumes:
                - redisdata:/data
            
    api:
        build: .
        container_name: task-api
        restart: always
        env_file:
            - .env
        ports:
            - "8000:8000"
        
        depends_on:
            - db
            - redis

        command: >
            sh -c "uvicorn backend.main:app --host 0.0.0.0 --port 8000"
        
        volumes:
            - .:/app
    
    airflow:
        image: apache/airflow:2.10.5

        container_name: task-airlow
        restart: always
        depends_on:
            - db
        environment:
            PYTHONPATH: /opt/airflow
            AIRFLOW__CORE__EXECUTOR: LocalExecutor
            AIRFLOW__DATABASE__SQL_ALCHEMY_CONN:
                postgresql+psycopg2://postgres:postgres@db:5432/airflow_db
            AIRFLOW__WEBSERVER__SECRET_KEY:
                my_super_secret_key
            DATABASE_URL:
                postgresql+psycopg2://postgres:postgres@db:5432/tasks_db
        volumes:
            - ./airflow/dags:/opt/airflow/dags
            - ./analytics:/opt/airflow/analytics
            - ./requirements-airflow.txt:/requirements-airflow.txt
        ports:
            - "8080:8080"
        command: >
            bash -c "
            pip install -r /requirements-airflow.txt &&
            airflow db migrate &&
            airflow scheduler &
            airflow webserver
            "
       
    
volumes:
    pgdata:
    redisdata:
      
    
        