
services:
    db:
        image: postgres:15
        container_name: task-db
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: tasks_db
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg-isready -U postgres -d tasks_db"]
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 10s
    
    redis:
            image: redis:7
            container_name: task-redis
            restart: always
            ports:
                - "6379:6379"
            volumes:
                - redisdata:/data
            
    api:
        build: .
        container_name: task-api
        restart: always
        env_file:
            - .env
        ports:
            - "8000:8000"
        
        depends_on:
            - db
            - redis

        command: >
            sh -c "uvicorn backend.main:app --host 0.0.0.0 --port 8000"
        
        volumes:
            - .:/app
        
    
    
    
volumes:
    pgdata:
    redisdata:
      
    
        