"""add completed_at to tasks

Revision ID: ecd94ab5c50f
Revises: f92469de3af4
Create Date: 2026-06-12 22:17:13.250218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecd94ab5c50f'
down_revision: Union[str, None] = 'f92469de3af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('tasks', 'completed_at')
    # ### end Alembic commands ###
